# Generated by Django 3.2.5 on 2021-08-17 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0003_auto_20210817_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=120)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('booked_slot', 'booked_slot'), ('cancelled_appoinment', 'cancelled_appoinment'), ('no_booking', 'no_booking')], default='no_booking', max_length=40)),
                ('user', models.CharField(max_length=40)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctors')),
            ],
        ),
    ]
