# Generated by Django 3.2.5 on 2021-08-17 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_auto_20210817_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='end_time',
            field=models.TimeField(max_length=250),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='start_time',
            field=models.TimeField(max_length=250),
        ),
    ]
